### ISSUE TITLE
Syntax error on valid command when reading .CAQ

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#75]
I get a syntax error when I load (or run) a .CAQ file that was created on either the OG Aquarius via USB BASIC or via any legacy emulator (VAQ or Aqualite). It seems to be when I have a SET FAST ON statement in the code. The issue is resolved if I re-type the line back in on the AQ+ itself, and save the file. The code runs perfectly after that. A couple of screen shots showing the issue...

![Screenshot from 2024-06-09 20-40-14](https://github.com/fvdhoef/aquarius-plus/assets/38511341/7e39c7a1-3fdf-459e-a781-88fb534b3a34)
![Screenshot from 2024-06-09 20-40-01](https://github.com/fvdhoef/aquarius-plus/assets/38511341/ba81d9d2-3da6-43f5-a27c-d1b3550c59eb)

**Comment by fvdhoef** [comment]
The SET FAST ON statement is plusBASIC specific. So if you type that in other BASIC versions it will be encoded as regular text instead of the correct plusBASIC tokens.

**Comment by LoudScotsBloke** [comment]
Hi. I know that set fast on is a plusbasic command. My code has clauses to only run those commands if an Aq+ is detected (and I am rubbing in a +). Those lines never run on the original Aquarius. If I retype the line, exactly the same... On the AQ+ it runs perfectly.

**Comment by fvdhoef** [comment]
I think you don't understand the point I'm trying to make. The binary CAQ format stores BASIC commands as tokens (single byte values), in the same way the program is stored in memory. So a statement such as PRINT is stored as a single byte instead of 5 characters. If you type a statement that is not recognized it will be stored in full (not tokenized) as separate bytes. So if you enter the 'SET FAST ON' on the legacy BASIC it will be stored as separate bytes instead of 3 tokens. When you try to run that code on an Aq+ it will see that as a syntax error. When you retype the line it is tokenized by plusBASIC as 3 tokens and then it can recognize the statement.

**Comment by LoudScotsBloke** [comment]
Ahh... Thank you for that explanation. That does make my life a little more difficult when writing stuff for both legacy and plus though. But I get why it doesn't work now. Thank you.

**Comment by LoudScotsBloke** [comment]
I did also notice that the token is different for the Locate command. It seems to be translated to 'down'

**Comment by LoudScotsBloke** [comment]
Although it makes my development process a wee bit more involved... I understand why this happens, and I am happy to close the ticket.
